name: CI main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  minitest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ruby-version:
          - "3.2"
          - "3.3"
          - "3.4"
        include:
          - os: ubuntu-latest
            ruby-version: jruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true # runs `bundle install` and caches installed gems automatically
      - run: bundle exec rake
